#!/usr/bin/env python
import rospy, roslib
from sensor_msgs.msg import Image
import cv2, cv_bridge


cap = cv2.VideoCapture(0);

while(1):
	
	ret, frame = cap.read()

	gr = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

	cv2.imshow('frame', gr)

rospy.init_node('gr')
Gray = gr()
rospy.spin()
